import test from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { cursorInstaller } from "../dist/libs/install/platforms/cursor.js";

function tempRepo() {
  const root = mkdtempSync(join(tmpdir(), "greplica-cursor-test-"));
  return {
    root,
    cleanup: () => rmSync(root, { recursive: true, force: true }),
  };
}

function withHome(home, callback) {
  const previousHome = process.env.HOME;
  process.env.HOME = home;
  try {
    return callback();
  } finally {
    if (previousHome === undefined) {
      delete process.env.HOME;
    } else {
      process.env.HOME = previousHome;
    }
  }
}

test("installs Greplica guidance and skills for Cursor", () => {
  const repo = tempRepo();
  try {
    const result = withHome(repo.root, () =>
      cursorInstaller.install({
        repo_root: repo.root,
        repo_name: "sample",
        default_branch: "main",
      }),
    );

    const rulePath = join(repo.root, ".cursor", "rules", "greplica.mdc");
    assert.deepEqual(result.rules?.configFiles, [rulePath]);
    assert.deepEqual(
      result.skills.map((skill) => skill.replace(repo.root, "<home>")).sort(),
      [
        "<home>/.cursor/skills/greplica-bootstrap/SKILL.md",
        "<home>/.cursor/skills/greplica-update-working-memory/SKILL.md",
      ],
    );

    const rule = readFileSync(rulePath, "utf8");
    assert.match(rule, /alwaysApply: true/);
    assert.match(rule, /greplica graph context/);
    assert.match(rule, /greplica-bootstrap/);
    assert.match(rule, /greplica-update-working-memory/);
  } finally {
    repo.cleanup();
  }
});

test("does not overwrite an existing user-authored Cursor rule", () => {
  const repo = tempRepo();
  try {
    const existingRule = join(repo.root, ".cursor", "rules", "greplica.mdc");
    mkdirSync(join(repo.root, ".cursor", "rules"), { recursive: true });
    writeFileSync(existingRule, "user-authored rule\n", "utf8");

    const result = withHome(repo.root, () =>
      cursorInstaller.install({
        repo_root: repo.root,
        repo_name: "sample",
        default_branch: "main",
      }),
    );

    assert.equal(readFileSync(existingRule, "utf8"), "user-authored rule\n");
    assert.equal(result.rules?.configFiles[0], join(repo.root, ".cursor", "rules", "greplica-1.mdc"));
    assert.match(readFileSync(result.rules.configFiles[0], "utf8"), /Generated by Greplica/);
  } finally {
    repo.cleanup();
  }
});
