import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { greplicaHookGuidance } from "../../hooks/guidance.js";
import {
  copyStringField,
  isRecord,
  renderSessionTranscriptMarkdown,
  sanitizeTranscriptMessage,
  type SessionTranscriptMessage,
} from "../../session-transcript/markdown.js";
import { packageRoot } from "../paths.js";
import { copyBundledSkills } from "../skills.js";
import type { PlatformInstallContext, PlatformInstallResult, PlatformInstaller, WorkingMemoryUpdateInput } from "./types.js";

const generatedMarker = "<!-- Generated by Greplica. -->";
const generatedPluginMarker = "Generated by Greplica.";
const clineSessionRefPrefix = "cline-task:";
const clinePluginGuidancePlaceholder = "\"__GREPLICA_HOOK_GUIDANCE__\"";

export const clineInstaller: PlatformInstaller = {
  platform: "cline",
  install({ repoRoot, hooks }: PlatformInstallContext): PlatformInstallResult {
    const skills = copyBundledSkills(join(repoRoot, ".cline", "skills"));

    const rulesDir = join(repoRoot, ".clinerules");
    mkdirSync(rulesDir, { recursive: true });
    const guidancePath = clineGuidancePath(rulesDir);
    writeFileSync(guidancePath, clineGuidance(), "utf8");

    if (!hooks) {
      return {
        skills,
      };
    }

    const pluginsDir = join(repoRoot, ".cline", "plugins");
    mkdirSync(pluginsDir, { recursive: true });
    const pluginPath = clinePluginPath(pluginsDir);

    writeFileSync(pluginPath, clinePlugin(), "utf8");

    return {
      skills,
      hooks: {
        platform: "cline",
        configFiles: [pluginPath],
        events: ["beforeModel"],
        command: "Cline plugin: Greplica beforeModel guidance",
      },
    };
  },
  sessionSourceRef(sessionId: string): string {
    return `${clineSessionRefPrefix}${sessionId}`;
  },
  sessionIdFromSourceRef(ref: string): string | undefined {
    return ref.startsWith(clineSessionRefPrefix) ? ref.slice(clineSessionRefPrefix.length) : undefined;
  },
  transcriptToMarkdown(transcript: string): string {
    return clineTranscriptToMarkdown(transcript);
  },
  async runWorkingMemoryUpdate(_input: WorkingMemoryUpdateInput): Promise<void> {
    throw new Error("Cline background working-memory updates are not supported yet.");
  },
};

function clineGuidancePath(rulesDir: string): string {
  const preferred = resolve(rulesDir, "greplica.md");
  if (!existsSync(preferred) || readFileSync(preferred, "utf8").includes(generatedMarker)) return preferred;

  for (let index = 1; index < 100; index += 1) {
    const candidate = resolve(rulesDir, `greplica-${index}.md`);
    if (!existsSync(candidate) || readFileSync(candidate, "utf8").includes(generatedMarker)) return candidate;
  }

  throw new Error(`Could not find a safe Cline rule path in ${rulesDir}.`);
}

function clinePluginPath(pluginsDir: string): string {
  const preferred = resolve(pluginsDir, "greplica.ts");
  if (!existsSync(preferred) || readFileSync(preferred, "utf8").includes(generatedPluginMarker)) return preferred;

  for (let index = 1; index < 100; index += 1) {
    const candidate = resolve(pluginsDir, `greplica-${index}.ts`);
    if (!existsSync(candidate) || readFileSync(candidate, "utf8").includes(generatedPluginMarker)) return candidate;
  }

  throw new Error(`Could not find a safe Cline plugin path in ${pluginsDir}.`);
}

function clineGuidance(): string {
  return `# Greplica Repo Memory

${generatedMarker}

Greplica provides local, searchable repository memory for this repo.

${greplicaHookGuidance}

- Greplica installs shared agent skills under \`.cline/skills/\`; use \`greplica-bootstrap\` for initial repo memory and \`greplica-update-working-memory\` near the end of useful sessions.
- Keep repository memory local unless the user explicitly chooses an external embedding provider.
`;
}

function clinePlugin(): string {
  const templatePath = join(packageRoot(), "libs", "install", "platforms", "assets", "cline-greplica-plugin.ts.template");
  return readFileSync(templatePath, "utf8").replace(clinePluginGuidancePlaceholder, JSON.stringify(greplicaHookGuidance));
}

function clineTranscriptToMarkdown(transcript: string): string {
  const parsed = JSON.parse(transcript) as unknown;
  const metadata: Record<string, string> = {};
  const events = clineTranscriptEvents(parsed, metadata);
  const messages: SessionTranscriptMessage[] = [];

  for (const event of events) {
    const role = clineTranscriptRole(event);
    if (role === undefined) continue;

    const message = sanitizeClineTranscriptMessage(clineTranscriptMessage(event));
    if (message.length === 0) continue;
    messages.push({
      timestamp: undefined,
      role,
      phase: undefined,
      message,
    });
  }

  return renderSessionTranscriptMarkdown({ metadata, messages });
}

function clineTranscriptEvents(parsed: unknown, metadata: Record<string, string>): unknown[] {
  if (Array.isArray(parsed)) return parsed;
  if (!isRecord(parsed)) return [];

  copyStringField(metadata, parsed, "taskId", "session_id");
  copyStringField(metadata, parsed, "task_id", "session_id");
  copyStringField(metadata, parsed, "cwd", "cwd");

  if (Array.isArray(parsed.apiConversationHistory)) return parsed.apiConversationHistory;
  if (Array.isArray(parsed.messages)) return parsed.messages;
  return [];
}

function clineTranscriptRole(event: unknown): SessionTranscriptMessage["role"] | undefined {
  if (!isRecord(event)) return undefined;
  if (event.role === "user") return "human";
  if (event.role === "assistant") return "agent";
  return undefined;
}

function clineTranscriptMessage(event: unknown): string {
  if (!isRecord(event)) return "";
  return clineTextContent(event.content);
}

function sanitizeClineTranscriptMessage(message: string): string {
  return sanitizeTranscriptMessage(message)
    .replace(/<environment_details>[\s\S]*?<\/environment_details>\s*/g, "")
    .trim();
}

function clineTextContent(value: unknown): string {
  if (typeof value === "string") return value.trim();
  if (!Array.isArray(value)) return "";

  const parts: string[] = [];
  for (const item of value) {
    if (typeof item === "string") {
      parts.push(item);
    } else if (isRecord(item) && item.type === "text" && typeof item.text === "string") {
      parts.push(item.text);
    } else if (isRecord(item) && item.type === "tool_result") {
      const content = clineTextContent(item.content);
      if (content.length > 0) parts.push(content);
    }
  }
  return parts.join("\n\n").trim();
}
