import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { copyBundledSkills } from "../skills.js";
import type { PlatformInstallContext, PlatformInstallResult, PlatformInstaller, WorkingMemoryUpdateInput } from "./types.js";

const generatedMarker = "<!-- Generated by Greplica. -->";
const generatedPluginMarker = "Generated by Greplica.";

export const clineInstaller: PlatformInstaller = {
  platform: "cline",
  install({ repoRoot, hooks }: PlatformInstallContext): PlatformInstallResult {
    const skills = copyBundledSkills(join(repoRoot, ".cline", "skills"));

    const rulesDir = join(repoRoot, ".clinerules");
    mkdirSync(rulesDir, { recursive: true });
    const guidancePath = clineGuidancePath(rulesDir);
    writeFileSync(guidancePath, clineGuidance(hooks), "utf8");

    if (!hooks) {
      return {
        skills,
        guidanceFiles: [guidancePath],
      };
    }

    const pluginsDir = join(repoRoot, ".cline", "plugins");
    mkdirSync(pluginsDir, { recursive: true });
    const pluginPath = clinePluginPath(pluginsDir);

    writeFileSync(pluginPath, clinePlugin(), "utf8");

    return {
      skills,
      hooks: {
        platform: "cline",
        configFiles: [pluginPath],
        events: ["beforeModel"],
        command: "Cline plugin: Greplica beforeModel guidance",
      },
      guidanceFiles: [guidancePath, pluginPath],
    };
  },
  sessionSourceRef(_sessionId: string): string {
    throw new Error("Cline session source refs are not supported yet.");
  },
  sessionIdFromSourceRef(_ref: string): string | undefined {
    return undefined;
  },
  transcriptToMarkdown(_transcript: string): string {
    throw new Error("Cline transcript projection is not supported yet.");
  },
  async runWorkingMemoryUpdate(_input: WorkingMemoryUpdateInput): Promise<void> {
    throw new Error("Cline background working-memory updates are not supported yet.");
  },
};

function clineGuidancePath(rulesDir: string): string {
  const preferred = resolve(rulesDir, "greplica.md");
  if (!existsSync(preferred) || readFileSync(preferred, "utf8").includes(generatedMarker)) return preferred;

  for (let index = 1; index < 100; index += 1) {
    const candidate = resolve(rulesDir, `greplica-${index}.md`);
    if (!existsSync(candidate) || readFileSync(candidate, "utf8").includes(generatedMarker)) return candidate;
  }

  throw new Error(`Could not find a safe Cline rule path in ${rulesDir}.`);
}

function clinePluginPath(pluginsDir: string): string {
  const preferred = resolve(pluginsDir, "greplica.ts");
  if (!existsSync(preferred) || readFileSync(preferred, "utf8").includes(generatedPluginMarker)) return preferred;

  for (let index = 1; index < 100; index += 1) {
    const candidate = resolve(pluginsDir, `greplica-${index}.ts`);
    if (!existsSync(candidate) || readFileSync(candidate, "utf8").includes(generatedPluginMarker)) return candidate;
  }

  throw new Error(`Could not find a safe Cline plugin path in ${pluginsDir}.`);
}

function clineGuidance(hooks: boolean): string {
  const hookGuidance = hooks
    ? "- Greplica installs a Cline plugin under `.cline/plugins/` with a `beforeModel` hook that injects graph-context guidance."
    : "- Cline hooks were not installed. Ask Cline to use `greplica graph context \"<question>\"` before broad exploration.";
  return `# Greplica Repo Memory

${generatedMarker}

Greplica provides local, searchable repository memory for this repo.

- Before broad manual exploration, run \`greplica graph context "<question>"\` with a focused natural-language query.
- Greplica installs shared agent skills under \`.cline/skills/\`; use \`greplica-bootstrap\` for initial repo memory and \`greplica-update-working-memory\` near the end of useful sessions.
${hookGuidance}
- Keep repository memory local unless the user explicitly chooses an external embedding provider.
`;
}

function clinePlugin(): string {
  return `// ${generatedPluginMarker}
import type { AgentPlugin } from "@cline/core";

type PluginHooks = NonNullable<AgentPlugin["hooks"]>;
type BeforeModelHook = NonNullable<PluginHooks["beforeModel"]>;
type BeforeModelContext = Parameters<BeforeModelHook>[0];
type AgentMessage = BeforeModelContext["request"]["messages"][number];

const guidanceMessage: AgentMessage = {
\tid: "greplica_guidance",
\trole: "user",
\tcreatedAt: Date.now(),
\tmetadata: {
\t\tkind: "greplica_guidance",
\t},
\tcontent: [
\t\t{
\t\t\ttype: "text",
\t\t\ttext: "Greplica hook guidance: greplica is a repo-memory search tool for finding relevant architecture, decisions, flows, and code anchors. Before broad manual exploration in this repository, run greplica graph context \\"<question>\\" with a focused natural-language query. When Greplica provides useful context, mention that you used it and briefly say what it helped with.",
\t\t},
\t],
};

const plugin: AgentPlugin = {
\tname: "greplica-repo-memory",
\tmanifest: {
\t\tcapabilities: ["hooks"],
\t},
\thooks: {
\t\tbeforeModel({ request }) {
\t\t\tif (request.messages.some((message) => message.id === guidanceMessage.id)) {
\t\t\t\treturn undefined;
\t\t\t}
\t\t\treturn {
\t\t\t\tmessages: [guidanceMessage, ...request.messages],
\t\t\t};
\t\t},
\t},
};

export { plugin };
export default plugin;
`;
}
