import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { PlatformInstallInput, PlatformInstallResult, PlatformInstaller, WorkingMemoryUpdateInput } from "./types.js";

const generatedMarker = "<!-- Generated by Greplica. -->";

export const clineInstaller: PlatformInstaller = {
  platform: "cline",
  install(input: PlatformInstallInput): PlatformInstallResult {
    const repoRoot = input.repo.repo_root ?? process.cwd();
    const rulesDir = join(repoRoot, ".clinerules");
    mkdirSync(rulesDir, { recursive: true });

    const guidancePath = clineGuidancePath(rulesDir);
    writeFileSync(guidancePath, clineGuidance(), "utf8");

    return {
      skills: [],
      guidanceFiles: [guidancePath],
    };
  },
  sessionSourceRef(_sessionId: string): string {
    throw new Error("Cline session source refs are not supported yet.");
  },
  sessionIdFromSourceRef(_ref: string): string | undefined {
    return undefined;
  },
  transcriptToMarkdown(_transcript: string): string {
    throw new Error("Cline transcript projection is not supported yet.");
  },
  async runWorkingMemoryUpdate(_input: WorkingMemoryUpdateInput): Promise<void> {
    throw new Error("Cline background working-memory updates are not supported yet.");
  },
};

function clineGuidancePath(rulesDir: string): string {
  const preferred = resolve(rulesDir, "greplica.md");
  if (!existsSync(preferred) || readFileSync(preferred, "utf8").includes(generatedMarker)) return preferred;

  for (let index = 1; index < 100; index += 1) {
    const candidate = resolve(rulesDir, `greplica-${index}.md`);
    if (!existsSync(candidate) || readFileSync(candidate, "utf8").includes(generatedMarker)) return candidate;
  }

  throw new Error(`Could not find a safe Cline rule path in ${rulesDir}.`);
}

function clineGuidance(): string {
  return `# Greplica Repo Memory

${generatedMarker}

Greplica provides local, searchable repository memory for this repo.

- Before broad manual exploration, run \`greplica graph context "<question>"\` with a focused natural-language query.
- When the user asks to use \`greplica-bootstrap\`, create initial repo memory by reading high-signal repo docs first, inspecting only the shallow source/config surfaces needed to verify durable facts, writing a focused proposal JSON, running \`greplica proposal validate <proposal.json>\`, asking before applying it, and then running \`greplica proposal apply <proposal.json>\`.
- When the user asks to use \`greplica-update-working-memory\`, update memory from the current session by checking \`git status --short\`, \`git diff --stat\`, focused diffs, touched docs, and existing memory from \`greplica graph context "<task or changed area>"\`; write a focused proposal JSON, run \`greplica proposal validate <proposal.json>\`, ask before applying it, and then run \`greplica proposal apply <proposal.json>\`.
- Cline hooks are not installed by Greplica yet, so background working-memory updates will not run automatically.
- Near the end of useful coding sessions, ask the user whether to run \`greplica-update-working-memory\` so durable decisions, constraints, changed flows, and follow-ups are saved.
- Keep repository memory local unless the user explicitly chooses an external embedding provider.
`;
}
