import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { RepoRef } from "../../knowledge-graph/service.js";
import { copyBundledSkills } from "../skills.js";
import type { PlatformInstallResult, PlatformInstaller, WorkingMemoryUpdateInput } from "./types.js";

const generatedMarker = "<!-- Generated by Greplica. -->";

export const cursorInstaller: PlatformInstaller = {
  platform: "cursor",
  install(repo: RepoRef): PlatformInstallResult {
    const repoRoot = repo.repo_root ?? process.cwd();
    const skills = copyBundledSkills(join(homedir(), ".cursor", "skills"));
    const rulesDir = join(repoRoot, ".cursor", "rules");
    mkdirSync(rulesDir, { recursive: true });

    const rulePath = cursorRulePath(rulesDir);
    writeFileSync(rulePath, cursorRuleContent(), "utf8");

    return {
      skills,
      rules: {
        platform: "cursor",
        configFiles: [rulePath],
      },
      notes: [
        "Cursor project guidance was installed. Reload Cursor if the new project rule is not picked up immediately.",
      ],
    };
  },
  sessionSourceRef(sessionId: string): string {
    return `cursor-session:${sessionId}`;
  },
  sessionIdFromSourceRef(ref: string): string | undefined {
    return ref.startsWith("cursor-session:") ? ref.slice("cursor-session:".length) : undefined;
  },
  transcriptToMarkdown(_transcript: string): string {
    throw new Error("Cursor transcript projection is not supported yet.");
  },
  async runWorkingMemoryUpdate(_input: WorkingMemoryUpdateInput): Promise<void> {
    throw new Error("Cursor background working-memory updates are not supported yet.");
  },
};

function cursorRulePath(rulesDir: string): string {
  const preferred = join(rulesDir, "greplica.mdc");
  if (!existsSync(preferred) || readFileSync(preferred, "utf8").includes(generatedMarker)) return preferred;

  for (let index = 1; index < 100; index += 1) {
    const candidate = join(rulesDir, `greplica-${index}.mdc`);
    if (!existsSync(candidate) || readFileSync(candidate, "utf8").includes(generatedMarker)) return candidate;
  }

  throw new Error(`Could not find a safe Cursor rule path in ${rulesDir}.`);
}

function cursorRuleContent(): string {
  return `---
description: Use Greplica repo memory when working in this project
globs:
  - "**/*"
alwaysApply: true
---
${generatedMarker}

Greplica stores long-term, searchable engineering memory for this repository.

Before broad manual exploration, run:

\`\`\`bash
greplica graph context "<focused question>"
\`\`\`

Use the returned components, flows, claims, and code anchors to decide where to inspect first.

For a repository without memory yet, ask the agent to use \`greplica-bootstrap\`.

Near the end of useful work sessions, ask the agent to use \`greplica-update-working-memory\` so durable decisions, constraints, changed workflows, and follow-up tasks are saved.

Do not store secrets, transient debugging chatter, or raw command logs as Greplica memory.
`;
}
